### ISSUE TITLE
Error message on MacOS on "aMI: Start Matlab"

### ISSUE THREAD

**Issue by AndersBarth** [marmottetranquille/aMi#44]
**Describe the bug**
VSC reports "Matlab remote control can not be initiated." as error message on MacOS, however all functionality seems to work.

`which matlab`, when run from terminal, returns 

> /Applications/MATLAB_R2018a.app/bin/matlab

This, however, seems not to be recognized as a valid path by the 'realpath' check on line 387 of extension.ts:

exec('realpath \`which matlab\`', (err: any, stdout: string, stderr: string) => {

**Comment by marmottetranquille** [comment]
Thanks for the report and nice to hear the extension also actually works also on MacOs :).

The test leading to this message causes more trouble than anything and at the end of the day it can indeed very well fail while everything run smoothly (eg. your case or if one has set a matlab alias to manage several versions); besides the message does not even relate to the "remote control" but simply to whether "matlab" command exists on the system => it shall be removed.
