### ISSUE TITLE
display variables in workspace even after the script is finished

### ISSUE THREAD

**Issue by LeoJhonSong** [marmottetranquille/aMi#48]
Hi, first this is really amazing work!
I think displaying the variables in the workspace in real time is a great idea. The command `who` (matlab command) may be used recursively to get the variables in warkspace now. There, the variables will be shown even if they are assigned in the interactive matlab, or after the script is finished.

**Comment by Jake-Moss** [comment]
I would also love for variables to be displayed somewhere within VS code too. Until then I think the command "workspace" will do what you want.
